In [ ]:
print("University of Michigan")

University of Michigan


In [ ]:
x1q3z9ocd = 35.0
x1q3z9afd = 13.6
x1q3p9afd = x1q3z9ocd - x1q3z9afd

print(x1q3p9afd)

21.4


In [ ]:
weekly_working_hours = 45
week_days = 5
lunch_day = 1

hours_day = (weekly_working_hours / week_days) + lunch_day

print(hours_day)

10.0


In [ ]:
x = 1 + 2 ** 3 / 4 * 5
print(x)

11.0


In [ ]:
word = "CarePito "
times = 3

word_x3 = word * times
print(word_x3.strip())

#word_plus3 = word + times
#print(word_plus3)

CarePito CarePito CarePito


In [ ]:
print(99/100)

0.99


In [ ]:
# Elevator Europ to US Floor number

Floor_number = input("Europe floor number? ")
floor_us = int(Floor_number) + 1

print(f"In the U.S the floor number is: {floor_us}")

Europe floor number? 2
In the U.S the floor number is: 3


In [ ]:
print(42 % 10)
print(int(98.6))

2
98


***
# Module 5

In [ ]:
astr = "12e35"

try:
  print("Here we go")
  istr = int(astr)
  print("Number converted")

except:
  istr = -1

print("Program finished", istr)

Here we go
Program finished -1


3.1 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.

In [ ]:
hrs_w = input("Enter number of worked hours: ")
rate_40 = input("Enter the rate per hour: ")

try:
  hrs = float(hrs_w)
  rate = float(rate_40)
except:
  hrs = 0
  rate = 0



if hrs > 40:
  rate_40plus = rate * 1.5
  plus_hours = hrs - 40
  payment = (40* rate) + (plus_hours * rate_40plus)
else:
  payment = hrs * rate

print(f"Payment: {payment}")

Enter number of worked hours: 45
Enter the rate per hour: 10.5
Payment: 498.75


3.3 Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:
Score Grade
>= 0.9 A
>= 0.8 B
>= 0.7 C
>= 0.6 D
< 0.6 F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.

In [ ]:
score = input("Enter the score: ")

try:
  score = float(score)
except:
  print("Please enter a number")
  quit()

if score < 0 or score > 1:
  print("Score out of range.")
  quit()
elif score < 0.6:
  grade = "F"
elif score < 0.7:
  grade = "D"
elif score < 0.8:
  grade = "C"
elif score < 0.9:
  grade = "B"
else:
  grade = "A"

print(grade)

Enter the score: l
Please enter a number
Score out of range.
Your score: -1 is a  grade


***
# Module 6
## Functions

In [ ]:
def print_lyrics():
  print("LLego la hora de partir, sin medir distancias")
  print("Y muy triste quedara mi corazon")

print_lyrics()

LLego la hora de partir, sin medir distancias
Y muy triste quedara mi corazon


In [ ]:
def greet(lang):

  lang = lang.upper()

  if lang == "RU":
    print("Hola en Ruso")
  elif lang == "FR":
    print("Hola en Frances")
  else:
    print("Que se dice mi perrito")

greet("jp")

Que se dice mi perrito


4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function

In [ ]:
def computepay(hrs_w,rate_40):
  try:
    hrs = float(hrs_w)
    rate = float(rate_40)
  except:
    hrs = 0
    rate = 0

  if hrs > 40:
    rate_40plus = rate * 1.5
    plus_hours = hrs - 40
    payment = (40* rate) + (plus_hours * rate_40plus)
  else:
    payment = hrs * rate

  return payment

computepay(45,10.5)

498.75

***
# Module 7
## Loops

In [ ]:
panas = ["Pana 1","Pana 2", "Pana 10", "Pana 20"]

for pana in panas:
  print(f"Que hizo: {pana}")

Que hizo: Pana 1
Que hizo: Pana 2
Que hizo: Pana 10
Que hizo: Pana 20


In [ ]:
from random import randint

number_list = []
for num in range(10):
  number_list.append(randint(5,500))

print(number_list)
largest_number = number_list[0]

for num in number_list:
  if num > largest_number:
    print(num)
    largest_number = num

print(largest_number)

[215, 340, 141, 436, 442, 144, 51, 484, 52, 329]
340
436
442
484
484


In [ ]:
from random import randint

number_list = []
for num in range(10):
  number_list.append(randint(5,500))

print(number_list)
smallest = None

for number in number_list:
  if smallest == None:
    smallest = number
  elif number < smallest:
    print(number)
    smallest = number

print(smallest)

[396, 405, 39, 225, 274, 337, 406, 89, 83, 232]
39
39


5.2 Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.

In [ ]:
largest_number = None
smallest_number = None

while True:
  number = input("Enter a number: ")

  if number.lower() ==  'done':
    print(f"Maximum is {largest_number}")
    print(f"Minimum is {smallest_number}")
    break

  try:
    number = int(number)
  except:
    print("Invalid input")
    continue

  if (largest_number == None) or (smallest_number == None):
    largest_number = number
    smallest_number = number
  elif number < smallest_number:
    smallest_number = number
  elif number > largest_number:
    largest_number = number


Enter a number: 7
Enter a number: 2
Enter a number: bob
Invalid input
Enter a number: 10
Enter a number: 4
Enter a number: done
Maximum is 10
Minimum is 2
